project:
  type: website
  output-dir: docs/

website:
  title: "María Bueno Álvez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: experience.qmd
        text: Experience
      - href: blog.qmd
        text: Blog
  page-footer:
    center: "© 2025 María Bueno Álvez"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual